version: '3.9'
services:
  translation-management-service:
    image: translation-management-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:translationdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always
